# 主题模式

theme:
  switch: true
  default: style-light

# 网站图标

favicon:
  logo: /img/logo.png
  icon16: /img/logo.png
  icon32: /img/logo.png
  appleTouchIcon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: false
  hidden: failure.ico
#   showText: (/≧▽≦/)嘿！骗你的！
#   hideText: (●—●)哎呀，崩溃了！

# 用户信息

user:
  name: Harry Dai # 侧边栏与其他位置的姓名标识
  first_name: Dai
  last_name:  Harry # 顶栏姓名标识
  avatar: img/avatar.png
  email: haorand16@gmail.com
  domain: https://www.haorandai.com/
  describe: Stay hungry, stay foolish.
  ruleText:

# 顶栏 | 导航栏 | TopBars

top_bars:
  - title: Home
    url: /

  - title: Articles
    url: /archives/
    noswup: true
    children:
      - title: year
        url: /archives/
      - title: Categories
        url: /categories/

  - title: Projects
    url: /links/
    noswup: true

  - title: About
    url: /about/
    noswup: true

#  - title: Comment
#    url: https://comment.shawn404.top/
#    noswup: true

# 侧栏

## 社交链接

sidebar:
  social:  # 社交地址
    - name: Github
      icon: fab fa-github
      url: https://github.com/haorandai

    - name: Linkedin
      icon: fab fa-linkedin
      url: https://www.linkedin.com/in/haorandai

    - name: Email
      icon: fab fa-email
      url: https://www.mailto:haorand16@gmail.com

#    - name: Chatroom(failed for now!)
#      icon: fa fa-comment
#      url: http://111.67.196.161/
#
#    - name: VS Code
#      icon: far fa-file-code
#      url: https://code.shawn404.top
#
#    - name: Calendar
#      icon: far fa-calendar-alt
#      url: https://cal.com/shawnnotfound

  #     - name: Live Book
  #       icon: far fa-edit
  #       url: https://livebook.shawn404.top

  ## 打字动画

  typedTextPrefix: Harry is a
  typedText: [ 'Developer', 'Dreamer', 'Photographer', 'Writer' ]

  ## 侧边信息

  info: # 个人信息
    - key: Ages
      val: 24
    - key: Address
      val: Boston, MA


# 横幅 Banner

banner:
  use_cover: true
  index:
    type: video
    bgurl: https://cdn.moji.com/websrc/video/autumn20190924.mp4
    bannerTitle: Talk is easy, </br> Show me the code!
    bannerText: Hi my friend! hope my content is helpful to you!

  archive:
    type: img
    bgurl: https://pic.imgdb.cn/item/63ba7f5cbe43e0d30ed4dad0.jpg

  about:
    type: img
    bgurl: https://pic.imgdb.cn/item/63ba97c1be43e0d30e0306c3.jpg

  links:
    type: img
    bgurl: https://pic.imgdb.cn/item/63ba7f83be43e0d30ed522ad.jpg


# 分类卡片

categorie_card:
  enable: true
  len: 2
  list: ['Blog','Plog']

# 归档页

archive:
  type: more # less more


# 页脚

footer:
  copyrightYear: 2024

  powered:
    enable: false

  live_time:
    enable: true
    prefix: footer.tips
    start_time: 04/01/2024 0:00:00

# 文章Artical

post_pagination:
  enable: true
  type: small # large || small


## 目录

toc:
  enable: true
  list_number: true
  max_depth: 4
  min_depth: 1

webAnalytics:
  enable: true
  google: G-XJ4CETQ39Z

# 百度SEO

baidu_push: true

google_push: true

# 评论

comment:
  twikoo:
    enable: false
    envId:  # 腾讯云环境id
    region: # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数
    option: # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数




# 链接页配置，请见 /source/_data/links.yml

# reward:
#   enable: true
#   comment: Buy me a coffee~
#   url: https://afdian.net/a/ShawnNotFound

reward:
  enable: false
  comment: Buy me a coffee~.
  methods:
    - name: 支付宝(推荐)
      path: https://s1.ax1x.com/2023/04/23/p9eWpeU.jpg
    - name: 微信
      path: https://s1.ax1x.com/2023/04/23/p9eW9wF.png


# 关于页

about:
  introduction:
  blog:
  privacy:


# 字数统计

wordcount:
  enable: true
  count: true
  time: true

# KaTeX

katex:
  copy_tex: true
  global: true
  options: {}

# 站内搜索
search:
  enable: true
  type: local

# Extensions
plugins:
  hexo-generator-feed


